import Head from 'next/head'
import React, { useContext, useEffect } from 'react'
import { Container } from '@mui/material'
import { AppContext } from '../../src/provider/index.provider'
import WelcomeAdmin from '../../src/components/Layouts/WelcomeAdmin.layout'
import CustomAlert from '../../src/components/elements/Alert'
import AdminContent from '../../src/components/Layouts/AdminContent.layout'

const Admin = () => {

    const { appState, setAppState } = useContext(AppContext)
    useEffect(() => {
        setAppState({...appState, model: {...appState.model, userlevel: 1}})    
    }, [])

    useEffect(() => {
        setAppState({...appState, model: {...appState.model, userlevel: 1}})    
    }, [appState.pageState.curLayout])

    return (
        <>
            <div style={appState.pageState.curLayout == "WelcomeLayout" ? appState.pageStyle.backgroundStyle1 : appState.pageStyle.backgroundStyle2}>
                <Head>
                    <title>Connexin - Health</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <CustomAlert />
                {appState.model.userlevel == 1 ? (<>
                    { appState.pageState.curLayout == "WelcomeLayout" ? (
                        <Container maxWidth="sm"><WelcomeAdmin /></Container>
                    ) : null }
                    { appState.pageState.curLayout == "AdminLayout" ? <AdminContent /> : null }
                </>) : null}
            </div>
        </>
    )
}

export default Admin
