import Head from 'next/head'
import React, { useContext, useEffect } from 'react'
import { Container } from '@mui/material'
import { AppContext } from '../provider/index.provider'
import Contest from './Layouts/Contest.layout'
import Main from './Layouts/Main.layout'
import Question from './Layouts/Question.layout'
import Welcome from './Layouts/Welcome.layout'
import CustomAlert from "./../components/elements/Alert"


const User = () => {
    
    const {appState, setAppState} = useContext(AppContext)

    useEffect(()=>{
        setAppState({...appState, model: {...appState.model, userlevel: 0}})
    }, [])

    return (
        <>
            <div style= { appState.pageState.curLayout == "WelcomeLayout" ? appState.pageStyle.backgroundStyle1 : appState.pageStyle.backgroundStyle2 }>
                <Head>
                    <title>Connexin - Health</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <CustomAlert />
                <Container maxWidth="sm">
                    {appState.model.userlevel == -1 ? <><div>Please check your Url</div></> : (
                        <>
                            {
                                appState.pageState.curLayout == "WelcomeLayout" ? <Welcome /> : null
                            }
                            {
                                appState.pageState.curLayout == "MainLayout" ? <Main /> : null
                            }
                            {
                                appState.pageState.curLayout == "QuestionLayout" ? <Question /> : null
                            }
                            {
                                appState.pageState.curLayout == "ContestLayout" ? <Contest /> : null
                            }
                        </>
                    )}
                </Container>
            </div>            
        </>
    )
}

export default User
