import React from "react"
import Head from 'next/head'
import { Box } from "@mui/material"
import ImageMark from "../src/components/elements/ImageMark"
import TextMark from "../src/components/elements/TextMark"


export default function Index(){
    const style = {
        height: "100vh", 
        flex: 1, 
        display: "flex", 
        flexDirection: "column", 
        justifyContent: "center", 
        alignItems: "center",
        paddingTop: "50px"
    }
    return (
        <>
            <Head>
                <title>Connexin - Health</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div style= { {
                padding: "0px 0px",
                minHeight: "100vh",
                background: "linear-gradient(#1559da, #3073ea, #5092ff)",
                textAlign: "center",
                flex: 1,
                display: "flex",
                flexDirection: "column"
            }}>
                <Box sx={style}>
                    <TextMark />
                    <ImageMark type={"big"} /> 
                </Box>
            </div>
        </>
    )
}